# config/services.yaml
parameters:
    user_api_url: 'http://localhost:5000'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $userApiUrl: '%user_api_url%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\Service\UserSyncService:
        arguments:
            $userApiUrl: '%user_api_url%'
            $entityManager: '@doctrine.orm.entity_manager'

    App\Controller\Api\AuthController:
        arguments:
            $userApiUrl: '%user_api_url%'